version: "3.9"

services:
  web:
    build: .
    command: python /lokimo_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lokimo_backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

