# Generated by Django 4.1.3 on 2022-11-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autoImported", models.BooleanField()),
                ("closedByUser", models.BooleanField()),
                ("highlighted", models.BooleanField()),
                ("is3dHighlighted", models.BooleanField()),
                ("isLeading", models.BooleanField()),
                ("onTheMarket", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250)),
                ("availableDate", models.CharField(blank=True, max_length=50)),
                ("balconyQuantity", models.IntegerField(null=True)),
                ("balconySurfaceArea", models.FloatField(null=True)),
                ("bathroomsQuantity", models.IntegerField(null=True)),
                ("bedroomsQuantity", models.IntegerField(null=True)),
                ("city", models.CharField(max_length=50)),
                ("exposition", models.CharField(blank=True, max_length=50)),
                ("floor", models.IntegerField(null=True)),
                ("floorQuantity", models.IntegerField(null=True)),
                ("gardenSurfaceArea", models.FloatField(null=True)),
                ("hasAirConditioning", models.BooleanField(null=True)),
                ("hasAlarm", models.BooleanField(null=True)),
                ("hasBalcony", models.BooleanField(null=True)),
                ("hasCaretaker", models.BooleanField(null=True)),
                ("hasCellar", models.BooleanField(null=True)),
                ("hasDoorCode", models.BooleanField(null=True)),
                ("hasElevator", models.BooleanField(null=True)),
                ("hasFirePlace", models.BooleanField(null=True)),
                ("hasGarden", models.BooleanField(null=True)),
                ("hasIntercom", models.BooleanField(null=True)),
                ("hasParquet", models.BooleanField(null=True)),
                ("hasPool", models.BooleanField(null=True)),
                ("hasSeparateToilet", models.BooleanField(null=True)),
                ("hasTerrace", models.BooleanField(null=True)),
                ("hasVideophone", models.BooleanField(null=True)),
                ("heating", models.BooleanField(null=True)),
                ("isInStudentResidence", models.BooleanField(null=True)),
                ("isRecent", models.BooleanField(null=True)),
                ("link", models.CharField(max_length=250)),
                ("newOrOld", models.CharField(blank=True, max_length=50)),
                ("newProperty", models.BooleanField()),
                ("opticalFiberStatus", models.CharField(blank=True, max_length=50)),
                ("outdoorParkingQuantity", models.IntegerField(null=True)),
                ("parkingPlacesQuantity", models.IntegerField(null=True)),
                ("priceWithoutFees", models.IntegerField()),
                ("publicationDate", models.CharField(max_length=50)),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("showerRoomsQuantity", models.IntegerField(null=True)),
                ("terracesQuantity", models.IntegerField(null=True)),
                ("thresholdDate", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=250)),
                ("toiletQuantity", models.IntegerField(null=True)),
                ("transactionType", models.CharField(max_length=250)),
                ("yearOfConstruction", models.IntegerField(null=True)),
                (
                    "status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("buy", models.BooleanField()),
                ("city", models.CharField(max_length=50)),
                ("first_date", models.CharField(max_length=50)),
                ("good_id", models.CharField(max_length=50)),
                ("house", models.BooleanField()),
                ("iris", models.CharField(max_length=50)),
                ("last_date", models.CharField(max_length=50)),
                ("meter_square", models.IntegerField()),
                ("price", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("surface", models.IntegerField()),
                (
                    "data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.data",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisement.position",
                    ),
                ),
            ],
        ),
    ]
