# Generated by Django 4.1.3 on 2022-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="heating",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
    ]
