# Generated by Django 4.1.3 on 2022-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0002_alter_data_heating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="priceWithoutFees",
            field=models.IntegerField(null=True),
        ),
    ]
