# Generated by Django 4.1.3 on 2022-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0004_alter_data_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
