# Generated by Django 4.1.3 on 2022-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0005_alter_data_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="heating",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="data",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
