# Generated by Django 4.1.3 on 2022-11-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0006_alter_data_heating_alter_data_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="position",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.position",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="priceWithoutFees",
            field=models.FloatField(null=True),
        ),
    ]
