# Generated by Django 4.1.3 on 2022-11-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0008_alter_advertisement_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="position",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.position",
            ),
        ),
    ]
