# Generated by Django 4.1.3 on 2022-11-30 14:03

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0009_alter_advertisement_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="position",
            name="lng",
        ),
        migrations.AddField(
            model_name="position",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                srid=4326,
            ),
        ),
    ]
